package com.morris.aurum.configurations;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.PropertySource;

/**
 * This file is generated by the aurum maven archetype and used to create beans of your application's
 * secrets to reuse throughout your web application. You can follow the general format and add secrets
 * to 'backend/src/main/resources/secrets.properties'.
 */
@Configuration
@PropertySource("classpath:secrets.properties")
public class ApplicationPropertiesConfiguration {

    @Value("${secrets.mongodbUri}")
    private String mongodbUri;

    @Bean
    public String mongodbUri() {
        return this.mongodbUri;
    }
}
