package com.morris.aurum.utils;

import com.morris.aurum.configurations.ApplicationPropertiesConfiguration;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.stereotype.Component;

/**
 * This Application Configuration Util is generated by aurum maven archetype and used to easily access
 * your applications properties. This file can be safely deleted/ignored if unused throughout your
 * application. It's recommended that this is deleted if unused.
 */
@Component("applicationConfigurationUtil")
public class ApplicationConfigurationUtil {

    public ApplicationPropertiesConfiguration getApplicationPropertiesConfiguration() {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(ApplicationPropertiesConfiguration.class);
        return context.getBean(ApplicationPropertiesConfiguration.class);
    }
}
