package com.morris.aurum.utils;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.networknt.schema.JsonSchema;
import com.networknt.schema.JsonSchemaFactory;
import com.networknt.schema.SpecVersion;
import com.networknt.schema.ValidationMessage;
import org.json.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.*;
import java.util.Set;

/**
 * The Json Validation Util is a utility class generated by aurum maven archetype to help validate
 * mongodb json schemas against java class objects.
 * <br><br>
 * You can review a default json-schemas of the default {@link com.morris.aurum.models.Base} class
 * at 'backend/src/main/resources/schemas/Base.json'.
 * <br><br>
 * For further information about json schema validation specifications you should see
 * <a href="https://json-schema.org/specification">Json Schema Specifications</a>
 */
@Component("jsonValidationUtil")
public class JsonValidationUtil {
    private static final Logger LOGGER = LoggerFactory.getLogger(JsonValidationUtil.class);

    /**
     * Ensures that any given object is valid against a given schema validation model.
     *
     * @param schemaPath {@link String} path to schema validation model
     * @param o {@link Object} The object to validate
     * @param clazz {@link Class} the object's class
     *
     * @return boolean - if the object is valid or not valid
     */
    public boolean isValidJsonSchema(String schemaPath, Object o, Class<?> clazz) {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new JavaTimeModule());
        JSONObject jsonObject = null;
        try {
            if (clazz == o.getClass()) {
                jsonObject = new JSONObject(objectMapper.writeValueAsString(o));
            }
        } catch (JsonProcessingException e) {
            LOGGER.error("error processing json: {}", e.getMessage());
        }

        if (jsonObject != null) {
            JsonSchemaFactory validatorFactory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V4);

            try (InputStream schemaStream = inputStreamFromSchemaPath(schemaPath)) {
                JsonSchema schema = validatorFactory.getSchema(schemaStream);
                JsonNode objectJsonFinal = objectMapper.readTree(inputStreamFromJSONObject(jsonObject));
                Set<ValidationMessage> validationResult = schema.validate(objectJsonFinal);
                if (validationResult.isEmpty()) {
                    return true;
                } else {
                    LOGGER.info("Validation Results on object class: {}", o.getClass());
                    validationResult.forEach(vm -> LOGGER.info(vm.getMessage()));
                    return false;
                }
            } catch (IOException e) {
                LOGGER.error("error processing json input stream: {}", e.getMessage());
            }
        }
        return false;
    }

    private InputStream inputStreamFromSchemaPath(String path) throws FileNotFoundException {
        if (found(path)) {
            String p = resolvePath(path);
            File resolvedFile = new File(p);
            return new FileInputStream(resolvedFile);
        }
        return null;
    }

    private InputStream inputStreamFromJSONObject(JSONObject jsonObject) {
        return new ByteArrayInputStream(jsonObject.toString().getBytes());
    }

    private String resolvePath(String filename) {
        File file = new File(filename);
        return  file.getAbsolutePath();
    }

    private boolean found(String path) {
        String p = resolvePath(path);
        File file = new File(p);
        return file.exists();
    }
}


